volumes:
  etc_wireguard:

services:
  wg-easy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - PROXY_USER_NAME=${PROXY_USER_NAME}
        - PROXY_GROUP_NAME=${PROXY_GROUP_NAME}
        - PROXY_GID=${PROXY_GID}
        - PROXY_UID=${PROXY_UID}

    env_file:
      - .env

    environment:
      - PUID=${PUID}
      - PGID=${PGID}

      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=${WG_HOST}

      # Optional:
      # hash of admin
      - PASSWORD_HASH=${WG_PW}
      # - PASSWORD_HASH=$$2a$12$59wdtpB/hZBWIFCIfPG5UeR0lU3GM.wlS3.e88gdENa.fyOgbuF9C
      - PORT=${WG_WEB_PORT}
      - WG_PORT=${WG_PORT}
      # - WG_CONFIG_PORT=92820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=0.0.0.0/0 # 192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    # image: ghcr.io/wg-easy/wg-easy
    image: wg-easy-ssh:latest
    container_name: wg-easy-ssh
    volumes:
      - ./ssh:/home/${PROXY_USER_NAME}/.ssh
      # - ./sshd_config:/etc/ssh/sshd_config
      # - ./wireguard:/etc/wireguard
    ports:
      - ${WG_PORT}:${WG_PORT}/udp
      - ${WG_WEB_PORT}:${WG_WEB_PORT}/tcp
      - ${WG_SSHD_PORT}:22
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
